---
author:
  - 'yowcow <yowcow@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0.98
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PSGI-sample
no_index:
  directory:
    - inc
    - t
requires:
  Plack: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
